#!/usr/bin/env bash
# =============================================================================
# adapters/pi/adapter.sh - Pi coding agent platform adapter
# =============================================================================
# Pi reads AGENTS.md at the project root as its operating manual and discovers
# skills from .pi/skills/ (project) or ~/.pi/agent/skills/ (global).
#
# We emit:
#   - AGENTS.md at the dist root (dispatcher with routing table)
#   - .pi/commands/<name>.md (command bodies, tool-neutralized)
#   - .pi/references/ (ai-first-rules.md and other shared specs)
#   - .pi/scripts/ (Python helpers)
#   - .pi/skills/obsidian-second-brain/SKILL.md (pi skill manifest)
# =============================================================================

PI_PLATFORM="pi"
PI_DIR="pi"
PI_DISPATCHER="AGENTS.md"

adapter_build() {
  local src="$1" dst="$2"

  _pi_emit_dispatcher "$src" "$dst"
  _pi_translate_commands "$src/commands" "$dst/.${PI_DIR}/commands"
  _pi_copy_references "$src/references" "$dst/.${PI_DIR}/references"
  _pi_copy_scripts "$src/scripts" "$dst/.${PI_DIR}/scripts"
  _pi_emit_skill "$src" "$dst/.${PI_DIR}/skills/obsidian-second-brain"
  _pi_emit_install_hint "$dst"
}

# Emit AGENTS.md at the dist root. Pi reads this at startup.
_pi_emit_dispatcher() {
  local src="$1" dst="$2"
  local out="$dst/$PI_DISPATCHER"

  {
    cat <<'EOF'
# Obsidian Second Brain - Pi Operating Manual

This vault runs the **obsidian-second-brain** skill. The skill ships a set of
*commands*: each one is a multi-step instruction file that you (the Pi agent)
should follow when the user's request matches its trigger phrase.

## How to operate

1. Read `_CLAUDE.md` in the vault root, if it exists, to learn the user's
   vault conventions (folder map, daily note format, naming).
2. When the user's request matches a trigger in the tables below, read the
   matching file under `.pi/commands/<name>.md` and follow its instructions
   step by step.
3. Treat the AI-first vault rule (`references/ai-first-rules.md`) as
   non-negotiable for every note you write: `## For future Claude` preamble,
   rich frontmatter (`type`, `date`, `tags`, `ai-first: true`), `[[wikilinks]]`
   for every person/project/concept, recency markers per external claim,
   sources verbatim, confidence levels where applicable.
4. Do not invent commands. If no command matches, ask the user what they
   want or fall back to plain natural-language help.

## Command routing tables (grouped by category)
EOF

    emit_routing_table_grouped "$src/commands" "$PI_PLATFORM" ".pi/commands"
    emit_trigger_reference     "$src/commands" "$PI_PLATFORM"

    cat <<'EOF'

## Trigger conventions

Each command file has a leading paragraph that documents its trigger phrases
in plain English. Treat those triggers as primary; the slash-form `/name` is
also accepted if the user types it.

## Scripts

Python helpers live under `.pi/scripts/`. They run via `uv run -m
scripts.research.<name>` from the vault root (or wherever the skill is
installed). The commands that need them reference the exact invocation
inside the command body.

## Skill invocation

This skill is also available as a pi skill. Use `/skill:obsidian-second-brain`
to load the full operating manual on demand.

---

*Generated by adapters/pi/adapter.sh - do not edit manually.*
EOF
  } > "$out"
}

# Copy commands into .pi/commands/, neutralizing Claude-specific tool
# names so the instructions still make sense for Pi's tool set.
_pi_translate_commands() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"
  local f out
  for f in "$src"/*.md; do
    [[ -f "$f" ]] || continue
    should_include "$f" "$PI_PLATFORM" || continue
    out="$dst/$(basename "$f")"
    cp "$f" "$out"
    rewrite_tool_neutral "$out"
    rewrite_platform_paths "$out" "$PI_DIR"
  done
}

_pi_copy_references() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"
  cp -R "$src/." "$dst/"
  find "$dst" -type f -name '*.md' -print0 | while IFS= read -r -d '' f; do
    rewrite_platform_paths "$f" "$PI_DIR"
  done
}

_pi_copy_scripts() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"
  cp -R "$src/." "$dst/"
}

# Emit a pi skill manifest so the skill is discoverable via /skill:obsidian-second-brain.
_pi_emit_skill() {
  local src="$1" dst="$2"
  mkdir -p "$dst"

  # Build a condensed description from the command list for the skill frontmatter
  local cmd_count
  cmd_count=$(ls "$src/commands"/*.md 2>/dev/null | wc -l)

  cat > "$dst/SKILL.md" <<SKILLEOF
---
name: obsidian-second-brain
description: >
  Operate any Obsidian vault as a living, self-rewriting second brain.
  Use this skill whenever the user asks to read, write, update, search, or
  manage their Obsidian vault - including saving notes from conversation,
  creating daily entries, updating kanban boards, logging dev work, managing
  people notes, capturing decisions, tracking deals, or maintaining any vault
  structure. Also triggers when the user wants to bootstrap a new vault from
  scratch, run a vault health check, or drop a _CLAUDE.md into their vault so
  all Claude surfaces share the same operating rules. Includes a research
  toolkit (7 commands: /x-read, /x-pulse, /research, /research-deep,
  /notebooklm, /youtube, /podcast) for AI-powered research. ${cmd_count}
  commands total across 4 layers: vault management, thinking tools, research
  toolkit, and meta/ops.
---

# Obsidian Second Brain (Pi Skill)

This is the pi skill manifest for obsidian-second-brain. For the full operating
manual, read \`AGENTS.md\` at the vault root. For the canonical vault-write
rule, read \`.pi/references/ai-first-rules.md\`.

## How to use

When the user's request matches a command trigger, read the corresponding file
under \`.pi/commands/<name>.md\` and follow its instructions step by step.

## Key rules

- **AI-first vault rule** (non-negotiable): every note you write must follow
  \`.pi/references/ai-first-rules.md\`. Preamble, frontmatter, wikilinks,
  recency markers, sources verbatim, confidence levels.
- **Search before create**: never create a duplicate; never claim absence
  from memory.
- **Propagate everything**: every write updates linked notes, the index, and
  the operation log.
- Do not invent facts. Mark unknowns as \`TBD\`.

## Command reference

See the routing tables in \`AGENTS.md\` at the vault root for the full list of
commands grouped by category.
SKILLEOF
}

_pi_emit_install_hint() {
  local dst="$1"
  cat > "$dst/INSTALL.md" <<'EOF'
# Install on Pi

```bash
# After running `bash scripts/build.sh --platform pi`:
cp -R dist/pi/. /path/to/your/vault/
```

Then in your vault:

- `AGENTS.md` is the operating manual Pi reads at session start.
- `.pi/commands/*.md` are the command bodies the AI follows when a matching
  trigger fires.
- `.pi/references/` holds the AI-first vault rule spec.
- `.pi/scripts/` holds the Python helpers invoked by the research toolkit
  commands. Run them via `uv run -m scripts.research.<name>`.
- `.pi/skills/obsidian-second-brain/SKILL.md` is the pi skill manifest,
  invocable via `/skill:obsidian-second-brain`.

Start Pi from the vault root. The skill loads automatically via AGENTS.md
and the `.pi/skills/` directory.

## Project-local install (recommended)

For per-project vaults, copy the built tree into each project root:

```bash
cp -R dist/pi/. /path/to/your/project/
```

Pi discovers `.pi/` and `AGENTS.md` by walking up from the current directory,
so the skill is available whenever you start Pi from that project.
EOF
}
